apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: bgc-git-source
spec:
  type: git
  params: 
  - name: url
    value: https://github.com/msmagnanijr/tdc-tekton
  - name: revision
    value: master

---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: bgc-image-blue
spec:
  type: image
  params: 
  - name: url
    value: "image-registry.openshift-image-registry.svc:5000/demo/tdc-app:3.0"
