apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
   name: mvn-test
spec:
  inputs:
   resources:
    - name: source
      type: git
   params:
   - name: contextDir
     description: the context dir within source
     default: .
   - name: mavenMirrorUrl
     description: the maven mirror url
     default: http://repo1.maven.apache.org/maven2   
   - name: destinationImage
     description: Parameter Description
     default: "$(outputs.resources.builtImage.url)"
   - name: dockerFile
     description: Parameter Description
     default: Dockerfile
  outputs:
   resources:
    - name: builtImage
      type: image
  stepTemplate:
    resources:
      limits:
        cpu: 250m
        memory: 2Gi
      requests:
        cpu: 250m
        memory: 2Gi
    securityContext:
       allowPrivilegeEscalation: false
       privileged: false
       # the default underprivileged user to be used
       runAsUser: 10001
  steps:
   - name: build-sources
     image: quay.io/rhdevelopers/tutorial-tools:0.0.2
     workingDir: "/workspace/source/quarkus-pipeline/$(inputs.params.contextDir)"
     args:
      - mvn      
      - clean 
      - compile
     env:
     - name: MAVEN_MIRROR_URL
       value: "$(inputs.params.mavenMirrorUrl)"
  volumes:
  - name: varlibc
    emptyDir: {}