apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: deploy
spec:
  inputs:
    params:
    - name: yq-image
      description: yq CLI container image to run this task
      default: docker.io/mikefarah/yq
    - name: ARGS
      type: array
    - name: kubernetesResourceFile
      default: Deployment.yml
    resources:
    - name: image
      type: image
    - name: source
      type: git      
  steps:
  - name: kubctl-deploy
    image: quay.io/rhdevelopers/tutorial-tools:0.0.2
    command: ['kubectl']
    args:
    - rollout 
    - latest 
    - dc/blue