apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: bgc-git-source
spec:
  type: git
  params: 
  - name: url
    value: https://github.com/burrsutter/blue-green-canary
  - name: revision
    value: master